### ISSUE TITLE
Variable "id" does not exist for checkboxes

### ISSUE THREAD

**Issue by john-henry** [roundhouse/FormBuilder-2-Craft-CMS#1]
When using checkboxes as a field for a form I get the following template error on the front-end

I'm using **craft25** branch of FormBuilder 2 and Craft Client 2.5.2720

> Variable "id" does not exist 

**/craft/plugins/formbuilder2/templates/inputs/checkbox.twig(9)**

```twig
<label{% if required is defined and required %} class="required"{% endif %}{% if id %} for="{{ id }}"{% endif %}>

**Comment by owldesign** [comment]
Fixed.
