### ISSUE TITLE
When activated, I am unable to add / edit Craft fields locally.

### ISSUE THREAD

**Issue by m-soyka** [roundhouse/FormBuilder-2-Craft-CMS#10]
I noticed that when the "Form Builder 2" plugin is activated, I am unable to create a new field or edit any existing fields without there being a 500 Internal Server Error. I trouble shot this to better understand if it is the plugin or the way my environment is configured. I discovered that this problem goes away once the "Form Builder 2" plugin is disabled. However, I tried your first "Form Builder" and learned it does not create this error. I wanted to make you aware of this and look forward to using the new "Form Builder 2" in the future. Let me know if this is confusing or if you have any follow up questions.

**Comment by owldesign** [comment]
You know I'm not exactly sure what it could be because it seems to work fine for me. Could you tell me more about your environment? Are you running locally or on server somewhere? what php version you on?

**Comment by m-soyka** [comment]
I am developing locally using MAMP PRO version 3.4 with php 5.6.10

**Comment by m-soyka** [comment]
I think I figured it out. I wasn't working on the most recent Craft version, so when I updated it the FormBuilder 2 plugin worked correctly. Appreciate the help and the plugin.

**Comment by owldesign** [comment]
Glad you figured out, and thanks!
