### ISSUE TITLE
Success/Error Messages with Multiple AJAX Forms

### ISSUE THREAD

**Issue by Visiluna** [roundhouse/FormBuilder-2-Craft-CMS#100]
I have two forms on one page, both set to submit using AJAX. Each form is added to the page using an {% include %} tag. I did that to try to avoid any sort of confusion during parsing and rendering.

When either form is submitted, the Success/Error message area is updated for BOTH forms.

The forms otherwise appear to function correctly. Each form posts it's data to the correct form entry area and email notifications are sent as expected.

**Comment by Visiluna** [comment]
I suspect this is related to Issue #92.

**Comment by owldesign** [comment]
Fixed.
