### ISSUE TITLE
Fields used in multiple forms can't have different field templates

### ISSUE THREAD

**Issue by matthillco** [roundhouse/FormBuilder-2-Craft-CMS#101]
I'm not sure if this is a bug, or if I'm using the plugin incorrectly:

I have two forms, both of which use the same field named `message`. In one form, the field uses the custom field template `textarea`, while in the other form the field template is `textarea-wide`.

But this doesn't seem to work: both forms render the field with the same template (seems to be whichever field template was last saved in the Edit form > Fieldset screen).

Is this the expected behaviour?

**Comment by owldesign** [comment]
This sounds like an expected behavior. A field will only be able to have one value for `customTemplate` set. Sounds like it just keeps getting overwritten..

I'll take a look at it thought, maybe I can make custom fields take multiple `customTemplate` values based and related them to form id's

**Comment by matthillco** [comment]
OK, thanks, that makes sense. I can get around it by creating separate fields, I just thought I could save some time by re-using fields :)

**Comment by owldesign** [comment]
@matthillco you can now use different templates on the same field (across multiple forms)
