### ISSUE TITLE
Releases / tags

### ISSUE THREAD

**Issue by billythekid** [roundhouse/FormBuilder-2-Craft-CMS#102]
Just a suggestion rather than a bug or anything. I downloaded the latest release and it was 0.1.0, meaning the docs weren't quite aligned. Couldn't work out how to make custom html that wasn't in /templates/custom/input etc. Things were missing.

It might be an idea to update your releases in addition to setting the tags on them to prevent future downloaders running into this problem as tags are collapsed by default in github.

HTH

**Comment by owldesign** [comment]
Release updated, I've never used that before, thanks for pointing that out.
