### ISSUE TITLE
Editable Table

### ISSUE THREAD

**Issue by billythekid** [roundhouse/FormBuilder-2-Craft-CMS#103]
Is there any way to get an editableTable field into this as it stands?

I was thinking it would be easy enough to ask users to 'add a row' in the templates/js (or directly copy the editableTable template include from core) but even setting a table field to use a text input template doesn't render anything, even though the form builder allows us to add the table field.

Would just be an array of rows to be sent to the back end I think so saving shouldn't be difficult, with that in mind is there any workaround you can think of I could use at the moment to save "an array of text/textarea inputs" as a form field?

**Comment by owldesign** [comment]
Unfortunately not into this version of the plugin, sorry :(
