### ISSUE TITLE
Edit page on PHP 5.3

### ISSUE THREAD

**Issue by dubcanada** [roundhouse/FormBuilder-2-Craft-CMS#108]
Not a 100% sure if it is related to PHP 5.3 but on my server the _edit.twig inside `templates/forms` won't show the JS/CSS from the header partial. I need to manually add it to the top of _edit.twig

```
{% includeCssResource "formbuilder2/css/formbuilder2.css" %}
{% includeCssResource "formbuilder2/css/font-awesome.css" %}
{% includeJsResource "formbuilder2/js/plugins.js" %}
{% includeJsResource "formbuilder2/js/formbuilder2.js" %}
```

**Comment by owldesign** [comment]
I'm not sure, seems to work fine. I'm closing this one since one else is experiencing this issue. If the issue persists, please reopen and I'll troubleshoot further.
