### ISSUE TITLE
Feature request: download uploaded assets

### ISSUE THREAD

**Issue by lboaretto** [roundhouse/FormBuilder-2-Craft-CMS#109]
In the list of uploaded files, it's possible, by giving two clicks, to have the normal Craft popup. It would be interesting to have an option to download the files.

Thanks!!!

**Comment by ax2000** [comment]
+1 on this feature

**Comment by owldesign** [comment]
Latest push gives you ability to download all uploaded files.

![screen shot 2018-02-22 at 11 09 04 am](https://user-images.githubusercontent.com/438764/36559114-d6d55054-17c1-11e8-90a8-89b113619fab.png)
