### ISSUE TITLE
Link to the file uploaded broken on the email notification

### ISSUE THREAD

**Issue by fduarte** [roundhouse/FormBuilder-2-Craft-CMS#11]
Hi! Thanks for the plugin!

Have you noticed that if you upload a file with the form, you'll get an email notification with a section called "File Uploads" but the link to the file uploaded goes to "uploads/<FILENAME>" which means we get a 404.

Also, the file name should probably be modified so that special characters don't break the link. For example, if the file name uploaded includes dashes or spaces, the file name will break.

**Comment by owldesign** [comment]
Not exactly sure why it doesn't work for you, here's a vid of me going through it step by step and it works fine. I already have it set up so spaces are replaced with dashes. And the asset folder will be automatically created in your `public` directory. What php you running?

https://www.youtube.com/watch?v=IE2r5n4yV7M&feature=youtu.be

**Comment by fduarte** [comment]
Thanks a lot for putting that video together. I'll be testing it soon and I'll report back. Thanks!

**Comment by owldesign** [comment]
@fduarte you check it yet? want to close the ticket.

**Comment by owldesign** [comment]
Also no more links, email should have files as attachments now. I'm closing this issue for now. If it comes up again we can reopen.
