### ISSUE TITLE
Feature request: Custom recipient, such as custom subject

### ISSUE THREAD

**Issue by disco666** [roundhouse/FormBuilder-2-Craft-CMS#111]
Hey there,

it would be great if the recipient of a submission was customizable such as the subject.

Thanks and kind regards,
Lars

**Comment by owldesign** [comment]
You can customize subject line for recipients. `Email Subject`
![customsubject](https://user-images.githubusercontent.com/438764/28234130-2cab6218-68b1-11e7-8b25-7bd5b5902144.png)
