### ISSUE TITLE
Ajax form submitting twice

### ISSUE THREAD

**Issue by Reddogdesigns** [roundhouse/FormBuilder-2-Craft-CMS#113]
Form data is being submitted twice when using Ajax

**Comment by owldesign** [comment]
Can you tell me more? Are you using multiple forms on the same page?

**Comment by Reddogdesigns** [comment]
Hi,

Just a single form on this page:

http://www.gdnielsen.com/contact-us

The form submits but results in duplicate entries in the system along with duplicate notifications to the admin.

Thanks

Mike

--
Michael Hughes
Reddogdesigns

w: www.reddogdesigns.ca
e: mhughes@reddogdesigns.ca
t:  604.787.5328

**Comment by owldesign** [comment]
Can you post here or email me screenshots of your forms Email Settings. Specifically I want to see how your have your Admin and Submitter notification settings setup?

vadim@owl-design.net

**Comment by owldesign** [comment]
Also I pushed up new updates today and ajax submissions have changed. I would try to pull and see if you still have issue.

**Comment by owldesign** [comment]
Im closing this one, it was unrelated to the plugin.
