### ISSUE TITLE
500 error with notify admin

### ISSUE THREAD

**Issue by rizzledizzle** [roundhouse/FormBuilder-2-Craft-CMS#114]
After updating to the latest version, if i try and turn on Notify Admin, an error is thrown. Using your sampleForm.twig and a basic form with 3 plain text inputs, if i turn off Notify Admin form submits fine and my redirect works. if i turn it on, a 500 error is thrown in the console: POST http://url.com/actions/formBuilder2/entry/submitEntry 500 (Internal Server Error). Any ideas what i'm doing wrong or what might be causing that?

**Comment by owldesign** [comment]
Can you post screenshots of your form settings? Please attach all tabs, I need to recreate your form.

**Comment by rizzledizzle** [comment]
Hi thanks for getting back to me so quickly :) ignore the first post as i had rolled back to a previous version to try and fix my original issue so the above diagnoses is wrong.

So, my original issue was that redirects to a url had stopped working on form submission. having played around more, i have diagnosed the problem - if ajax submission is switched on, redirects to a url do not work (but the email notification works fine). if ajax submission is turned off, both email notification and redirect work as expected. im sure the combo of ajax+redirect urls worked previously as every form on our live site has that turned on, and they worked at some point. settings here:

http://imgur.com/a/uc8Rj 

for now its not too major an issue as i can turn of ajax submission on the relevant forms, just wondered if that was something anyone else could recreate or if its something with my implementation.

**Comment by owldesign** [comment]
Ok, I'll check..but, why do you use ajax if you will be redirecting anyways? Why not just stick to regular post?

**Comment by rizzledizzle** [comment]
that is a good question :) another developer had set up and installed the plugin, so i'm just working things out now - i think as you say its better to just switch of ajax as it sort of defeats the purpose if you are redirecting to another page.

**Comment by owldesign** [comment]
Yeah, now that we talked about it, I think I will try to disable redirects when ajax is switched on because there is no reasons for them at that point.. 

If that fixes it, can you close issue please.
