### ISSUE TITLE
Check performAction after entry service onBeforeSave event raised

### ISSUE THREAD

**Issue by mark-adigital** [roundhouse/FormBuilder-2-Craft-CMS#115]
Hi,

I was hoping to be able to write a plugin to prevent form entries from being written to the database. You have provided the `onBeforeSave` event in the Entry Service but this doesn't currently check the status of `performAction` before saving the entry, could this be added please?

Many thanks,

Mark

**Comment by owldesign** [comment]
There are functionalities during form submission that require a database entry. I would need to refactor that functionality...with that said, it'll will probably take me sometime to do that.

**Comment by mark-adigital** [comment]
Thanks for getting back to me. Ok, would it be any easier if some new event was raised after submission so I could delete the entry from the database through an event listener at that stage?

**Comment by owldesign** [comment]
@mark-adigital I added event you can use, here's usage example:

```
craft()->on('formBuilder2.onAfterSubmissionCompleteEvent', function(Event $event) {
        $entryId = $event->params['entryId'];
        craft()->formBuilder2_entry->deleteEntryById($entryId);
});
```
