### ISSUE TITLE
Class 'Craft\FormBuilder2_OnBeforeSaveEntryEvent' not found

### ISSUE THREAD

**Issue by mark-adigital** [roundhouse/FormBuilder-2-Craft-CMS#117]
Hi again,

Thanks for adding that new event in, however I tried updating our version of the plugin today and hit an issue with the forms (AJAX submissions):

```
Internal Server Error

Class 'Craft\FormBuilder2_OnBeforeSaveEntryEvent' not found
```

Would be grateful if this could be resolved.

Thanks,

Mark

**Comment by owldesign** [comment]
Please pull, latest pull request has fixed the typo in the class.
