### ISSUE TITLE
Bad Request - Again

### ISSUE THREAD

**Issue by martinsmith** [roundhouse/FormBuilder-2-Craft-CMS#119]
Hi there,
We installed and tested the plugin some time ago during a website development.  We updated to the latest version a few weeks ago but have only just come to test.  We're getting the following error only when using AJAX:

Bad Request - The request could not be understood by the server due to malformed syntax.

I've seen this issue has come up previously and seems to have come back.

Any advice appreciated.

**Comment by mrnebbi** [comment]
We're also getting these bad request errors when trying to submit the form with AJAX

**Comment by owldesign** [comment]
I am refactroing a lot of the code right now and will be updating the ajax submissions as well..

**Comment by mrnebbi** [comment]
Thanks @owldesign! Appreciate the work, but any idea of timeline? Using FormBuilder in a project due to go live shortly, and still having issues with the contact form setup.

**Comment by owldesign** [comment]
@mrnebbi It'll be some time for the new update, its a pretty big update.

If you can email me your db dump and the craft template files, I can try and track down the issue..

vadim@owl-design.net

**Comment by joepagan** [comment]
Does this not fix the issue? https://github.com/roundhouse/FormBuilder-2-Craft-CMS/issues/5#issuecomment-320213443

**Comment by joepagan** [comment]
I think it's because is because the default template you provide doesn't actually output the required form scripts?

**Comment by owldesign** [comment]
I'll be closing this, for people who ajax still broken please write your own javascript code to catch form submission and process it via ajax. I'm thinking of taking it out completely and just writing docs on how to implement it
