### ISSUE TITLE
Field type not updated when adding new form

### ISSUE THREAD

**Issue by ockam** [roundhouse/FormBuilder-2-Craft-CMS#12]
I’m testing FB2 on Craft 2.5.2755 with PHP7. When using the Forms field type, the list of forms that appear in the drop down doesn’t update when I add new forms. It shows only the forms that were already there when I created the field.

Am I missing something?

**Comment by owldesign** [comment]
Good catch, should be fixed now. 

Also I don't know if I documented it, but to use the Forms field type on the front end you can do it like this `{{ craft.formbuilder2.getFormById(entry.addForm) |raw }}` the `addForm` being the name of your field handle
