### ISSUE TITLE
Craft 3 Compatibility

### ISSUE THREAD

**Issue by ethanmuller** [roundhouse/FormBuilder-2-Craft-CMS#121]
Hey there!

Are there any plans to make this plugin compatible with Craft 3?

I've done some poking around in closed issues and branches and I couldn't find any evidence of it, but I figured it's worth asking.

**Comment by owldesign** [comment]
Yes, I have plans to convert this to Craft 3. No real roadmap right now though.. Right now I'm refactoring current plugin and once that is done, I will be working on craft 3 version.

thanks.
