### ISSUE TITLE
Notify Admin is also sending submitter an e-mail

### ISSUE THREAD

**Issue by RitterKnightCreative** [roundhouse/FormBuilder-2-Craft-CMS#123]
If I turn off notify admin and submitter, I don't get anything as expected.

If I turn on notify admin, both the admin and the submitter are getting identical e-mails.

**Comment by RitterKnightCreative** [comment]
OK update on this... traced it back to the Custom e-mail field, if you set that, it's adding the submitter's e-mail address as well to the send queue. 

![screen shot 2017-09-23 at 11 54 07 am](https://user-images.githubusercontent.com/3707869/30775274-f41f1426-a055-11e7-80c9-fea1e5fe93d9.png)

**Comment by owldesign** [comment]
Yeah that seems to be expected functionality. 

I'm working on a better version of this plugin so I'll clean all this confusing up. I'll close this ticket for now.
