### ISSUE TITLE
Pulling Notify Admin Email from Entry

### ISSUE THREAD

**Issue by jefffulton** [roundhouse/FormBuilder-2-Craft-CMS#124]
There is a form on every page of a Channel. I need the notification to go to the recipient listed on that channel entry. Is it possible for the form to get the notification email sent to {{ entry.groupLeaderEmail }}?

**Comment by owldesign** [comment]
Not exactly sure what you are are asking. Can you give me more details or usecase example?

**Comment by jefffulton** [comment]
Sorry about that... I've created profile channel for people in the organization (name, email, photo, etc). I've placed the form on each individual page, and I would like it to send a notification to the profile's email; in this case {{ entry.groupLeaderEmail }}. So, I would like the notification email address to be pulled from an entry on the page itself.

Here is an example page from the channel: http://connective.church/connective-moms
I need "Liz" in the case to be a recipient.

**Comment by jefffulton** [comment]
`<input type="hidden" name="recipient" value="{{ entry.groupLeaderEmail }}">`
in the template is rendering as 
`<input type="hidden" name="recipient" value="lizf@fultondesign.net">`
... but I tried the form and it didn't go through. 

Do I need to do something special in Forms > Email Settings > Notification Email?
I currently have that set to {{ entry.groupLeaderEmail }}

**Comment by jefffulton** [comment]
Forgot to mention. I uninstalled and deleted the plug-in... and did a fresh install.

**Comment by owldesign** [comment]
Yeah you'd have to have Admin Notifications turned on the form, is that toggled on?

**Comment by jefffulton** [comment]
I do.
![screen shot 2017-09-21 at 4 00 52 pm](https://user-images.githubusercontent.com/29638703/30722440-187345a2-9ee6-11e7-95b4-6d1fafbc09c6.png)

**Comment by owldesign** [comment]
Its probably thorwing the error somehwere. You need to put in some email address into `Notification Email` that won't work and might break, that field is expecting a valid email value (is there a generic email you can put there?). 

And I wouldn't set anything for the `Custom Email Field` that is meant for a select dropdown field on the frontend where a user can pick their inquery type. For example if you have multiple departments, you can setup and drpdown field with value as the email address and label for the department name. When user select specific department, that department will get notification.

I suspect if you change those 2 fields it should go through?

**Comment by jefffulton** [comment]
still no... If that is what "Custom Email Field" does, then could I put the field .groupLeaderEmail into there, and just set it in the template as a hidden field?

**Comment by owldesign** [comment]
Nah it doesn't work like that, the functionality isn't there for it to work that way. Trying to think what it might be, I've tested this route on my end and it was working.

**Comment by owldesign** [comment]
I'm workig on a better version of this plugin and I'll make sure I set something up to achive this simplier. 

For now, you can try and hack the plugin code, this way we can be for certain there isn't something else going on..

If you are comfortable to edit the code open up `formbuilder2/services/FormBuilder2_EntryService.php` and add the following code after the line # `345`
Enter this code `$toEmails = array('lizf@fultondesign.net');`

Save and try the form again, let me know if the email goes through?

**Comment by jefffulton** [comment]
That didn't work either. I'll keep playing with the code, and let you know if I figure something out. Thank you for your assistance. It was WAY beyond my expectation.

**Comment by owldesign** [comment]
im going to close this issue, its specific to use case and not what the pluign offers right now.
