### ISSUE TITLE
Adding extra columns in entries overview

### ISSUE THREAD

**Issue by samverdyck** [roundhouse/FormBuilder-2-Craft-CMS#129]
Is there a best practice for adding datacolumns into the entries overview table?
For example adding a column "mail" and "name", to identify the entry better. (and no need to open each entry to search one)

**Comment by owldesign** [comment]
Unfortunately not with this plugin, [this rewrite of the plugin](https://github.com/owldesign/Form-Builder) will let you have field columns.
