### ISSUE TITLE
Submitted data as tags in email templates

### ISSUE THREAD

**Issue by atomworks** [roundhouse/FormBuilder-2-Craft-CMS#135]
When I'm using a template as a notifier, is there any way to add submitted content in to it? 

For example if I have a field such as firstName on my form, is there anyway to include that field to do something like "Hi [firstName]" so in the email it comes out as "Hi Leonard"

I need to have flexibility like this over the notifiers but I can't find anything documented or in these issues. I may be missing the obvious here.

**Comment by owldesign** [comment]
You won't be able to use submission variables like that in this plugin unfortunately. 

However, its a future I can add to the updated version of the plugin here https://formbuilder.tools/

I'm only going to be fixing bugs in this version of plugin but not adding new features. You should try the next version for best results.
