### ISSUE TITLE
Translate |t the label for frontend fields

### ISSUE THREAD

**Issue by simonfranzen** [roundhouse/FormBuilder-2-Craft-CMS#138]
Currently we have to override als frontend input fields and just add `|t` after the label. Shoudnt this be something of the core ?

example:

https://github.com/roundhouse/FormBuilder-2-Craft-CMS/blob/3675f5f820bb748f5a1925ee82d46bdc878f6c5b/formbuilder2/templates/inputs/text.twig#L11

to

`{{- label|raw|t -}}`

**Comment by owldesign** [comment]
added
