### ISSUE TITLE
Users cannot delete submissions

### ISSUE THREAD

**Issue by matt-adigital** [roundhouse/FormBuilder-2-Craft-CMS#146]
This feature works on one of our older sites running Craft 2.6.3000 and formbuilder 2.0.16. However after upgrading on another site to Craft 2.7.0 and formbuilder 2.0.22 we are now seeing an issue.

I'm logging in as the user and then trying to delete a submission. This user has access to this section and the Allow non-admins setting is also enabled. The delete button is shown but when clicked we recieve an error message stating: "Unauthorized: You don’t have the proper credentials to access this page."

Deleting a submission still works when I'm signed in as an admin but the client would like to have the functionality back to remove submissions themselves. Please let me know if you need any further information about this bug. Thank you.

**Comment by owldesign** [comment]
@matt-adigital I've pushed up a fix, non admins should be able to delete now if setting is enabled.

**Comment by matt-adigital** [comment]
Thank you for the quick response @owldesign I've tested and can confirm that the issue is fixed now.
