### ISSUE TITLE
Textarea?!

### ISSUE THREAD

**Issue by brycekirk** [roundhouse/FormBuilder-2-Craft-CMS#147]
How do you make a field appear as a textarea, as opposed to the WYSIWYG editor or one-line text?

**Comment by owldesign** [comment]
When you creating the field in Craft Fields are you selecting Plain Text field and checking the `Allow line breaks`?

**Comment by brycekirk** [comment]
That's what I was looking for, thanks!

**Comment by brandondeweese** [comment]
This works, but it ignores the "initial rows count". Is there a way to fix this?
