### ISSUE TITLE
File uploads should respect dynamic upload locations set in asset fields

### ISSUE THREAD

**Issue by pixeljitsu** [roundhouse/FormBuilder-2-Craft-CMS#15]
Awesome plugin.  Thanks a bunch.

This is probably a feature request, but it is an issue that is causing me problems with how the uploaded files are being organized.

When uploading a file, dynamic file locations should be respected as configured in the asset field settings.  Additionally an option to either replace existing files or renaming uploaded files should be added to the form options.

**Comment by owldesign** [comment]
@pixeljitsu file uploads now use dynamic folder location for uploads. You can also rename uploaded files via the submission entry page by double clicking the name or the thumb..


![screen shot 2016-08-02 at 2 02 46 pm](https://cloud.githubusercontent.com/assets/438764/17345217/dbfcd14c-58b9-11e6-8311-3fa2f50dc46e.png)
