### ISSUE TITLE
Get Form by ID instead of Handle

### ISSUE THREAD

**Issue by emcacace** [roundhouse/FormBuilder-2-Craft-CMS#16]
I was wondering how I could get a form object with an ID. The getFormById function behaves differently than the getFormByHandle. What I'm trying to do is have a user pick an existing form within an entry. Unfortunately right now, the only data I get is the ID of the form. If getFormById returned $form it would work fine. Thoughts? 
```
/**
	 * Get Form By Id
	 * 
	 */
	public function getFormById($formId)
	{
		$form = craft()->formBuilder2_form->getFormById($formId);
        
		$variables['formId'] = $form;

		craft()->path->setTemplatesPath(craft()->path->getPluginsPath().'formbuilder2/templates');
		$html = craft()->templates->render('/forms/frontend', $variables);
		craft()->path->setTemplatesPath(craft()->path->getTemplatesPath());
    
    return $html;
	}
	
	/**
	 * Get Form By Handle
	 * 
	 */
	public function getFormByHandle($formHandle)
  {
    return craft()->formBuilder2_form->getFormByHandle($formHandle);
  }```

**Comment by owldesign** [comment]
Please pull. I updated the function, it shouldn't have been that in the first place. You can use `getFormById($formId)` to get `form` object. If you need to render form html based on form ID on frontend (twig) you can use `getFormHtmlById($formId)`. Let me know if that fixed for you so I can close ticket.

**Comment by emcacace** [comment]
Great! It works. That was fast, thanks!

**Comment by owldesign** [comment]
no problem, happy to help.
