### ISSUE TITLE
Undefined options when adding Form to Matrix Field

### ISSUE THREAD

**Issue by emcacace** [roundhouse/FormBuilder-2-Craft-CMS#17]
To replicate, create a new Matrix field and add a Form to one of the nodes. Save the Matrix field and add to a section. In the Admin side, try create a new entry for that section. you get a php error

` undefined index: options  `

In the FormBuilder2FieldType.php, checking for options if they are set would fix this. 

```
/**
	 * @inheritDoc IFieldType::getInputHtml()
	 *
	 * @param string $name
	 * @param mixed  $value
	 *
	 * @return string
	 */
	public function getInputHtml($name, $value)
	{
		$field = craft()->fields->getFieldByHandle($name);

		return craft()->templates->render('formbuilder2/fieldtypes/forms/html', array(
			'name'    => $name,
			'value'   => $value,
            'options' => $field->settings['options']			
		));
	}

```

**Comment by owldesign** [comment]
I'll get back with a fix soon.

**Comment by owldesign** [comment]
Latest push should fix this.

**Comment by owldesign** [comment]
Im reopening this for now, looks like something still broken

**Comment by owldesign** [comment]
Nevermind silly me. On the front end have to use {{ craft.formbuilder2.getFormHtmlById(entry.addForm) |raw }}.. new function is `getFormHtmlById()`
