### ISSUE TITLE
Dropdown fields are not coming through when submitted

### ISSUE THREAD

**Issue by jimmylorunning** [roundhouse/FormBuilder-2-Craft-CMS#18]
Create a form with a dropdown on it. Put it on a page template. Fill out the form and submit it. Look at submitted entries, and you will see that the dropdown value was not sent.

And if you made it a required field, it won't let you submit the form at all, even if you have selected a value from the drop down.

**Comment by owldesign** [comment]
Will take a look

**Comment by owldesign** [comment]
Fixed, please pull latest.

**Comment by jimmylorunning** [comment]
Works great! Thanks :+1:
