### ISSUE TITLE
Required Checkboxes: won't let you submit unless the FIRST item of a series of checkboxes are checked

### ISSUE THREAD

**Issue by jimmylorunning** [roundhouse/FormBuilder-2-Craft-CMS#19]
I'm not sure what it means to have a checkboxes field be "required". But when I put it on a page and hit submit, it said I can't submit it until I check the box. But I had checked some boxes, just not the first one in the field. Apparently, unless the first box is checked, it considers it empty.

However, I think the ideal behavior would be if ANY of the boxes are checked, then it considers it filled. If NONE of the boxes are checked, AND it is a required field, it should give an error. That's just what my understanding would be. But some may argue that none of the checkboxes being checked is also a way of answering the question. So maybe in that case "required" doesn't hold any meaning at all.

**Comment by owldesign** [comment]
Required checkboxes is kind of weird, only way I was able to use it is by using javascript (http://parsleyjs.org/). I feel like I'd rather not use `required` attributes on checkboxes until there is better client-side validation (html5 input validations). 

I'll take a deeper look into it. See what craft is doing.

**Comment by cloudratha** [comment]
Any updates on this bug? Is it a plugin issue or a craft issue?

**Comment by owldesign** [comment]
@cloudratha techically its a checkbox issue, see here [ What does input.@required mean for @type = checkbox?](https://www.w3.org/html/wg/tracker/issues/111?changelog)

Best thing at the moment would be to not set checkboxes as `required` fields :(

**Comment by cloudratha** [comment]
Thanks for the update. I understand the limitations of a required checkbox. The issue we were having with the plugin is that with one checkbox field (with required), the form would not validate that it was checked even though it was a sent parameter. I've demo'd another plugin and it behaves as expected. Any thoughts?

**Comment by owldesign** [comment]
@cloudratha i pushed updated that should resolve your issue with only one checkbox.

**Comment by cloudratha** [comment]
Awesome. Thanks for that. Will let you know once I've tested it.
