### ISSUE TITLE
Background colour missing from Plugin admin page

### ISSUE THREAD

**Issue by john-henry** [roundhouse/FormBuilder-2-Craft-CMS#2]
The dark grey is missing from your header in branch craft25 and using Craft Client 2.5.2720

Or alternatively you could say the FormBuilder logo needs a darker colour :)

Tested in FF 42.0 , Chrome 46 and Safari 0.0.1

**Comment by owldesign** [comment]
Fixed for now, I'm still working on few fixes for craft 2.5 so some things might not work because I didn't get to them yet.
