### ISSUE TITLE
Templates Path screwed up once again

### ISSUE THREAD

**Issue by jimmylorunning** [roundhouse/FormBuilder-2-Craft-CMS#20]
I fixed this bug before, but it seems like it's back. After pulling in the form, if I then try to include a file, it won't find it because it's looking for it in the plugins path. I can fix this again if you want me to, let me know.

**Comment by owldesign** [comment]
Ops, I think i deleted it by accident. Should be good now.

**Comment by jimmylorunning** [comment]
Thanks!
