### ISSUE TITLE
Feat: Pass form params to thank you page

### ISSUE THREAD

**Issue by emcacace** [roundhouse/FormBuilder-2-Craft-CMS#22]
Hi, I was wondering what you thought of passing the form data to the thank you page. Sometimes, you might want to customize that page accordingly. I also thought it might be cool to integrate with other plugins like a mailchimp one, so for now I was going to have my redirect go to my mailchimp controller so I need the data. Maybe there is a better or easier way?

I was thinking in FormBuilder2_EntryController once the form validates (line 269), you can modify one line 
```
$this->redirect(array($redirectUrl, 'submission_data'=>$submission));
```

**Comment by owldesign** [comment]
I don't think I'm going to make mailchimp integration for this plugin. It might just need to be its own plugin. But I'll add so you can pass data to thank you pages sometime this week.

**Comment by emcacace** [comment]
Cool thanks. Yes I meant more to have a way for another plugin to easily hook to this one. Keep up the good work.

**Comment by owldesign** [comment]
Sounds good, I'm might need to go through the plugin and add bunch of hooks in appropriate spots so you guys can have access

**Comment by owldesign** [comment]
@emcacace I have added ability to pass submission data to the thank you pages.

https://github.com/roundhouse/FormBuilder-2-Craft-CMS#custom-redirects
