### ISSUE TITLE
Validation of textarea

### ISSUE THREAD

**Issue by jimmylorunning** [roundhouse/FormBuilder-2-Craft-CMS#23]
I have a textarea on my form, and it is "required". When I submit it without filling it in, it won't let me, but it also won't pop up the notification that that is what's wrong.

When I do the same with an input text field, I get a very helpful message "please fill out this field".

Is this a bug?

**Comment by owldesign** [comment]
Looks like a bug, will take a look at it later tonight.

**Comment by jimmylorunning** [comment]
Just messed around with it a little. If you turn javascript off, and change templates/input/richtest.twig so that there are no spaces between the opening and closing textarea tags (there is currently one space in there), then it works.

But when I turned javascript on again, and redactor gets filled in, it doesn't work anymore.

Hope this helps.

**Comment by owldesign** [comment]
@jimmylorunning took some time but latest should have it fixed, thanks.

**Comment by jimmylorunning** [comment]
Thanks @owldesign !
