### ISSUE TITLE
Pass additional parameters to email

### ISSUE THREAD

**Issue by danielparas** [roundhouse/FormBuilder-2-Craft-CMS#25]
Hi, thanks for the great plugin!

Is there a way to send additional parameters to the email. Eg. by using hidden fields in the form? 

I'm using the form for landing pages and I need to show which page the form was filled and sent from eg. by showing the url path as part of the form data in the email notification sent.

Thanks in advance
Daniel

**Comment by lexbi** [comment]
There appears to be a hidden.twig file in the inputs folder in this plugin, though I believe you will need to create your own field type for this as formbuilder2 currently uses the built in craft input types, and, "hidden" input type is currently not an option.

**Comment by lexbi** [comment]
So, create a new file at: `formbuilder2/fieldtypes/FormBuilder2_HiddenFieldType.php`

put this in your file:

        <?php
    namespace Craft;

    class FormBuilder2_HiddenFieldType extends BaseFieldType
    {
        public function getName()
        {
            return Craft::t('Hidden Field');
        }

        public function getInputHtml($name, $value)
        {
            return craft()->templates->render('formbuilder2/templates/inputs/hidden', array(
                'name'  => $name,
                'value' => $value
            ));
        }
    }

You can then create a new field within craft...

Then in this file `formbuilder2/variables/FormBuilder2Variable.php`, you'll need to add a new case for the new field type: 

    case "FormBuilder2_Hidden":
		if (IOHelper::fileExists($customTemplatePath . 'hidden' . $extension)) {
			$html = craft()->templates->render('formbuilder2/templates/custom/inputs/hidden', $variables);
		} else {
			$html = craft()->templates->render('formbuilder2/templates/inputs/hidden', $variables);
			}
		break;

Then it should output your input on the page.

**Comment by owldesign** [comment]
You can always just put in the hidden field manually... which would probably be better route so you don't have to duplicate the same form (in the cms) with different hidden fields. 

<input type="hidden" name="page" value="{{ pageTitleOrWhatever }}" />

**Comment by lexbi** [comment]
Would the value still save to the form submission?

**Comment by owldesign** [comment]
Yep, however there is extra step. Because I'm fetching craft fields to display submission data (or data sent to email) you will need to create a field in the CMS. Don't need to attach that field to the form just create it so its there.. For example..

`<input type="hidden" name="page" value="{{ entry.title }}">`

And create a custom field called `Page` with `page` handle. Thats it, your form submission will now show the "custom" hidden fields data

**Comment by lexbi** [comment]
Works great thanks!

**Comment by owldesign** [comment]
@danielparas I'm closing this issue, you can use instructions above.
