### ISSUE TITLE
Cant save Formular if enableCsrfProtection  is activated

### ISSUE THREAD

**Issue by phaetons** [roundhouse/FormBuilder-2-Craft-CMS#26]
I get an error like: "Could not check CSRF-Token" if i want to create/save a formular.

**Comment by owldesign** [comment]
Do you have `{{ getCsrfInput() }}` inside your `<form>` markup?

**Comment by phaetons** [comment]
Ah ok, the problem is in the backend / CP, so my frontend form markup is not relevant.
I meant that i cannot create a form in the backend if enableCsrfProtection is activated.

**Comment by owldesign** [comment]
I'll look into it tonight
