### ISSUE TITLE
Email Address Field type custom input

### ISSUE THREAD

**Issue by lexbi** [roundhouse/FormBuilder-2-Craft-CMS#29]
Hi Vadmin,

Thanks so much for your plugin, it's ace, just been trying it out and it doesn't look like there's any option for a custom field type?

For example: I want a field for "Email" but a custom field that has been added by myself or say "Sprout Fields" does not get picked up.

All I want to do is change the input "type" attribute to "email" so my custom validation.js can validate email addresses.

Can you suggest a way of doing this?

Thanks

**Comment by owldesign** [comment]
I dont have this as an option yet. But looking into building it in.

**Comment by glenwith1n** [comment]
I would love this option also, trying to do the same thing.

**Comment by glenwith1n** [comment]
I just made a quick fix for now, I made a custom template for text.twig and added an if statement in the type area.
`type="{% if label|raw == 'Email' %}email{%else%}text{% endif %}"`

**Comment by owldesign** [comment]
Added ability to use Sprout Fields (email, phone, hidden, link).
