### ISSUE TITLE
input text type

### ISSUE THREAD

**Issue by lexbi** [roundhouse/FormBuilder-2-Craft-CMS#31]
Hi Guys,

Noticed that the "type" attribute for a text field is incorrect. textarea/file fields appear fine, maybe it's just this one? Maybe the class/type fields are the wrong way around for this one?

![image](https://cloud.githubusercontent.com/assets/2337910/13171346/32f9fa4e-d6ea-11e5-9dba-aa036710e5ee.png)

**Comment by lexbi** [comment]
Ignore the class being "text1" was testing the custom html method you suggested in another issue.

**Comment by owldesign** [comment]
fixed this up. should be in the latest master. thanks!

**Comment by lexbi** [comment]
nice one bruv, cheers
