### ISSUE TITLE
Plugin Not Showing when Uploaded at server

### ISSUE THREAD

**Issue by FepAguilar** [roundhouse/FormBuilder-2-Craft-CMS#32]
I was working on my localhost enviroment and everything works fine until I've uploaded the whole project on the final server.

In this final server the plugin it's not appearing on plugin section. 

I've uploaded every file on craft/plugins but It is not showing on dashboard.

What could be happening?

Thanks in advance.

**Comment by theskyfloor** [comment]
Change the folder name to "formbuilder2"

**Comment by owldesign** [comment]
Hard to tell why that would happen. Yeah make sure the folder name is correct also are the php version and craft version similar between local and server?

**Comment by theskyfloor** [comment]
Make sure you also don't have caps in the folder name.

**Comment by tiborsaas** [comment]
Changing the folder name to "formbuilder2" solved it for me.

**Comment by owldesign** [comment]
Yeah plugin folder must be renamed to `formbuilder2`
