### ISSUE TITLE
Is it possible to use field's in notification settings?

### ISSUE THREAD

**Issue by theskyfloor** [roundhouse/FormBuilder-2-Craft-CMS#33]
I want to be able to send the confirmation to the form submitter as well as an admin. Is this possible?

I tried {owner.fieldHandle} and {entry.fieldHandle}

**Comment by theskyfloor** [comment]
Also do have any plans to add conditional fields? I love the design you have done so far on the backend!!

**Comment by owldesign** [comment]
Can't use twig fields in the settings. I can add another field in the settings where you can select the "Email" field from drop down of available fields on the form and plugin will use that to notify form submitter (if they of course enter email)

I love the idea of conditional fields, but that's a lot of work so maybe eventually I'll have some time to do that.. this guy is on the right track https://github.com/mmikkel/Reasons-Craft

**Comment by theskyfloor** [comment]
That would be rad! Any idea when you might be able to add that?

Yeah Reasons is great... I have been able to fake some conditionals with lightswitches in a Matrix attached to a form but something official from someone would be sweet.

**Comment by owldesign** [comment]
I'll be working on it in the next couple of days

**Comment by owldesign** [comment]
@theskyfloor Latest push has option to notify submitter.

This option will only show up if the form is saved with some fields added to it. Which means if you're creating a new form you wont see this option until you save the form and come back to edit it. 

Let me know if this worked for you and I can close issue.

**Comment by theskyfloor** [comment]
That's amazing! Works perfectly. We can close it... It would be sweet if it had the same options as the admin notification too but I can't complain because that was so fast. Thanks!

**Comment by owldesign** [comment]
This is a quick fix, but I plan on giving it similar configurations

**Comment by theskyfloor** [comment]
Sweet thanks! I love the admin interface you came up with for this. Super pleasant to work with...
