### ISSUE TITLE
Size attribute appears in markup even if empty

### ISSUE THREAD

**Issue by lexbi** [roundhouse/FormBuilder-2-Craft-CMS#34]
Just doing some w3c validation:
![image](https://cloud.githubusercontent.com/assets/2337910/13350549/9bfbd696-dc78-11e5-95a9-693beae2de91.png)

for: 
`<input      type="text"
          class="text" id="text-2101002558" size="" name="formName" value="" required  placeholder=""      autocomplete="off">`

It's moaning as the size attribute is empty. I notice in your text input template:
`{%- if max is defined %} size="{{ max }}"{% endif %}`

I've changed this to 

`{%- if max is defined and max|length > 0 %} size="{{ max }}"{% endif %}`

**Comment by owldesign** [comment]
updated, thanks!
