### ISSUE TITLE
Minified Redactor throws SyntaxError

### ISSUE THREAD

**Issue by knynkwl** [roundhouse/FormBuilder-2-Craft-CMS#35]
Changing `redactor.min.js` to `redactor.js` fixes the issue.

https://github.com/roundhouse/FormBuilder-2-Craft-CMS/blob/master/variables/FormBuilder2Variable.php#L34

```
Uncaught SyntaxError: Unexpected token var(anonymous function) @ redactor.min.js
Uncaught TypeError: $(...).redactor is not a function
```

**Comment by owldesign** [comment]
Hmm I'm not running into this error but if anyone else is having it this can be a temporary fix. Can you provide more info how you're getting this, what fields types your form contains and/or could it be a conflict with another js script you're running?

**Comment by knynkwl** [comment]
I tried removing all other scripts, and error still persists with `.min` file.

Here are the fields that I have http://grab.by/Ou3c

**Comment by owldesign** [comment]
closing this for now, if anyone run into this refer to above comments for a fix.
