### ISSUE TITLE
Get Undefined index: notifySubmitter

### ISSUE THREAD

**Issue by daituzhang** [roundhouse/FormBuilder-2-Craft-CMS#38]
Hi,
Thank you for bringing this amazing plugin to version 2.
I tried to create a new form after installing
however I get `Undefined index: notifySubmitter` error on saving the form

```php
/vagrant/craft/plugins/formbuilder2/services/FormBuilder2_FormService.php(157)

145     if ($spamProtectionSettings['spamHoneypotMethod'] != '' && $spamProtectionSettings['spamHoneypotMethodMessage'] == '') {
146       $form->addError('spamHoneypotMethodMessage', Craft::t('Please enter message for screen readers.'));
147     }
148     
149     if ($notificationSettings['notifySubmission'] == '1' && $notificationSettings['emailSettings']['notifyEmail'] == '') {
150       $form->addError('notifyEmail', Craft::t('Please enter notification email.'));
151     }
152 
153     if ($notificationSettings['notifySubmission'] == '1' && $notificationSettings['emailSettings']['emailSubject'] == '') {
154       $form->addError('emailSubject', Craft::t('Please enter notification email subject.'));
155     }
156 
157     if ($notificationSettings['notifySubmitter'] == '1' && $notificationSettings['submitterEmail'] == '') {
158       $form->addError('submitterEmail', Craft::t('Please select email field.'));
159     }
160     
161     $formRecord->validate();
162     $form->addErrors($formRecord->getErrors());
163 
164     if (!$form->hasErrors()) {
165       $transaction = craft()->db->getCurrentTransaction() === null ? craft()->db->beginTransaction() : null;
166       try {
167         if (!$isNewForm && $oldForm->fieldLayoutId) {
168           craft()->fields->deleteLayoutById($oldForm->fieldLayoutId);
169         }
```

I'm using Craft CMS 2.6.2776
Hope you have a better idea on what's happened.

Thank you!

**Comment by jbueler** [comment]
There is a fairly easy fix for this, I can help with a patch in the morning. It would essentially be something like this: 

```
if (isset($notificationSettings['notifySubmitter']) && ($notificationSettings['notifySubmitter'] == '1' && $notificationSettings['submitterEmail'] == '') {
    $form->addError('submitterEmail', Craft::t('Please select email field.'));
}
```

**Comment by builtbyvern** [comment]
Also experiencing the same problem on my end. I'll try that snippet out.

**Comment by owldesign** [comment]
@builtbyvern @daituzhang can you guys pull master and check if error was resolved?

**Comment by daituzhang** [comment]
@owldesign when click on formBuilder icon, get `Parse error: syntax error, unexpected '{' in /vagrant/craft/plugins/formbuilder2/services/FormBuilder2_FormService.php on line 157`

Thank you!

**Comment by owldesign** [comment]
@daituzhang oh gosh my bad! Can't believe I didn't double checked that. Should be good now

**Comment by daituzhang** [comment]
@owldesign all good! Thank you!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Macxim** [comment]
I'm still getting the same error.

**Comment by lexbi** [comment]
Just had this on the latest version of form builder from github & Craft CMS 2.6.2789

**Comment by owldesign** [comment]
@lexbi can you tell me which file you had this error in? I have something in place that shouldn't give you this error anymore hmm

**Comment by owldesign** [comment]
@lexbi try to pull latest again, I made an update.

**Comment by lexbi** [comment]
Hi again, no error message now, thanks for fixing so quickly!
