### ISSUE TITLE
Couple of queries - user email notification, validation, etc

### ISSUE THREAD

**Issue by nevsie** [roundhouse/FormBuilder-2-Craft-CMS#4]
I know this is a new one, i have just seen, so just general queries.

1 - typically the user entering the form, and the admin would receive a email notification. is this currently possible? i.e. different messages for user from admin

2 - validation of required and data entered - i see required, but is there more than this? Is the validation done using HTML 5, JS, or server side?

3 - export - can i export forms seperately, or only all at once?
And a side issue - do you use Yii / crafts object model for creating the download as with most other form plugins? if so this destroys memory, and PHP timeouts and usually prevent exports from working on large amount of entries!!!

**Comment by owldesign** [comment]
If its not an issue or a bug please just email me directly with questions.

1. User notification is not added yet, only admins can be notified. I'm still exploring best ways to do this.
2. Validation will happen server side on the fields that are `required` by default. This is also true if you are using Ajax to submit a form. HTML 5 browser validation work by default if browser don't support `required` attribute (safari) server side will validate the fields. No JS validation.
3. Exporting is also in the works, and I'm exploring options. Currently you can only export all submissions (entries). I'm not using Craft for exporting and downloading the .csv this is done with php's `fputcsv`
