### ISSUE TITLE
Undefined variable: path 

### ISSUE THREAD

**Issue by Macxim** [roundhouse/FormBuilder-2-Craft-CMS#40]
PHP Notice says the following:
```php
public function getTemplatesPath()
    {
        craft()->deprecator->log('PathService::getTemplatesPath()', 'PathService::getTemplatesPath() has been deprecated. Use TemplatesService::getTemplatesPath() or TemplatesService::getTemplateMode() instead.');
        return craft()->templates->getTemplatesPath($path);
    }
```

Craft CMS 2.6.2778

**Comment by owldesign** [comment]
Can you provide more info please, I have no idea where this is. It would be helpful if you can provide steps you took to get this notice and which file/path you're at while getting this error?

thanks.

**Comment by owldesign** [comment]
got it, i'll make these adjustments soon as i can, thanks!

**Comment by Macxim** [comment]
Yes, sorry.
I just copied the content of the sampleForm.twig and it gave me this error.
Sorry about the lack of explanation, I was fixing it.

**Comment by Macxim** [comment]
Do you want me to make a PR?

**Comment by owldesign** [comment]
please do, that would make it quicker for me
