### ISSUE TITLE
Restrict non-admins & ability to update name

### ISSUE THREAD

**Issue by knynkwl** [roundhouse/FormBuilder-2-Craft-CMS#42]
Any plans to add this functionality?

Similar to amnav plugin:
![screen shot 2016-03-31 at 10 57 47 am](https://cloud.githubusercontent.com/assets/4225771/14185589/7283b96a-f72f-11e5-93f1-4e9fc1f270d6.png)

**Comment by owldesign** [comment]
Hmm haven't thought about it, I can look into adding user role restrictions as well as updating the name of the plugin. Unfortunately don't have timeline, will work on it as soon as I get some free time!

**Comment by knynkwl** [comment]
Shweet! cheers

**Comment by owldesign** [comment]
@knynkwl plugin now has these functionalities.
