### ISSUE TITLE
Feature Request: Restrict to 1 entry daily per field

### ISSUE THREAD

**Issue by Nexcapto** [roundhouse/FormBuilder-2-Craft-CMS#43]
Do you think this would be too difficult to do? Mainly for contests and the like..

**Comment by owldesign** [comment]
@Nexcapto Yeah this is way too specific for what this plugin is meant for, I'd suggest developing a plugin just to do that. 

If you email me detailed description of this feature I might be able to make that plugin.

**Comment by Nexcapto** [comment]
Thank you for the quick reply. I appreciate that you'd be willing to give it a try, but I figured out a way to do it with guest entries.

**Comment by owldesign** [comment]
Perfect!
