### ISSUE TITLE
Configuration Blank Page

### ISSUE THREAD

**Issue by akukral** [roundhouse/FormBuilder-2-Craft-CMS#44]
After installing the plugin successfully FormBuilder2 is is appearing in the sidebar as well as on the settings page and in the plugins as installed and active. Unfortunately, I'm getting a completely blank page when I try to load the configuration or click on any links associated with FormBuilder2. Would you happen to have any ideas on how to address this?

**Comment by akukral** [comment]
It seems to be related to paths. I can access the configuration while developing locally at http://localhost:3000, but on my staging server it will not work. Is there a variable that I can change to make sure I'm loading the plugin from the right directory or location?

**Comment by owldesign** [comment]
@akukral make sure that the name of the plugin folder is exactly like this `formbuilder2` smaller case. Also what is the version of your craft install?

**Comment by carlosperez** [comment]
I'm having this issue as well. My initial problem had something to do with the folder name not being all lowercase. Now that I changed it, I uninstalled/reinstalled it and I still can't get the configuration page (as well as the actual form not working).

**Comment by carlosperez** [comment]
I'm seeing this in the logs:
```
2016/05/06 23:48:48 [warning] [application] The â€œFormBuilder 2â€ plugin release feed didnâ€™t come back as valid JSON:
```

followed by what looks bunch of HTML

**Comment by carlosperez** [comment]
The warning above was not related to the problem I was having (though I did open a PR to address that: https://github.com/roundhouse/FormBuilder-2-Craft-CMS/pull/49).

In the end, it was the version of PHP that I was running on the prod environment... I updated it to 5.5 and everything seems to be working now.
