### ISSUE TITLE
500 (Internal Server Error) on form AJAX submission

### ISSUE THREAD

**Issue by noahread** [roundhouse/FormBuilder-2-Craft-CMS#45]
When I submit a form from the front-end I get a 500 (Internal Server Error) for http://stage.liahonachildren.org/actions/formBuilder2/entry/submitEntry

I’ve tested my email setup, I’m using a 3rd party SMTP service, and it is working. Despite the error the new entry is showing up in the database, but no notification email is sent and the form stalls on _Sending…_ on the front-end.

**Comment by owldesign** [comment]
I'm having issues with ajax submissions too, I'll take a look as soon as I have time!

**Comment by tiborsaas** [comment]
I also experience this problem. Haven't looked under he hood yet. Backend email test is successfully sent via SMTP Amazon mail service.

**Comment by tiborsaas** [comment]
I found the reason. If I switch `omitScriptNameInUrls` in the general config to true, it stats working.

**Comment by noahread** [comment]
I think the problem I was having must be different. My `omitScriptNameInUrls` has been set to true from the beginning.

**Comment by owldesign** [comment]
I updated ajax submission functionality. Closing this for now.
