### ISSUE TITLE
email notification based on html select/dropdown value

### ISSUE THREAD

**Issue by shunluoifong** [roundhouse/FormBuilder-2-Craft-CMS#46]
I have a form that contains a select/dropdown field with a few different options. I would like the form submission notification to be sent to a different email based on what option is selected in the field. Is this possible with FormBuilder?

**Comment by owldesign** [comment]
@shunluoifong I dont have this ability yet, here's a similar ticket #39 where I made a field for sending email with custom subject.

I might need to add this feature though since more people are interested in it.

**Comment by shunluoifong** [comment]
@owldesign Thanks for the quick response! In my case I specifically need to send send notification to a different email based on the dropdown selection, so the custom subject won't work for me. Add my +1 for this feature request!

**Comment by owldesign** [comment]
@shunluoifong I have added this functionality.

Create dropdown field with option values as email addresses.

<img width="748" alt="dopdownfield" src="https://cloud.githubusercontent.com/assets/438764/17452340/3b488a90-5b23-11e6-88e5-df7688728543.png">

After you add it to the forms fields tab (save first) you can now choose that dropdown field to pull custom emails.

<img width="500" alt="customemaildropdownfield" src="https://cloud.githubusercontent.com/assets/438764/17452298/d150ae10-5b22-11e6-93a4-1d59b5f409e8.png">
