### ISSUE TITLE
Create a multi-page form

### ISSUE THREAD

**Issue by Sidneyvp** [roundhouse/FormBuilder-2-Craft-CMS#50]
I am trying to create a multi-page form.
On the first page, the customer can fill in all his required entries. Then the form should be passed to a new page where the customer fills in all of his personal information. Is it possible to do this or should it be done using javascript to show a particular part once the other part is finished?

**Comment by owldesign** [comment]
@Sidneyvp  Unfortunately what you suggesting cannot be accomplished with this plugin. You'd probably be better off writing some js for this type of functionality or a custom plugin.
