### ISSUE TITLE
Can't select custom logo when attempting HTML template option

### ISSUE THREAD

**Issue by joepagan** [roundhouse/FormBuilder-2-Craft-CMS#52]
Hi Again,

Just tried to select a logo within the HTML template area on a form.

It loads up the assets window, I can see all my asset sources though the files that definitely exist (I can see them in the asset manager) are not visible within this window. This is both the same for local asset sources & S3 asset sources.

The plugin
![image](https://cloud.githubusercontent.com/assets/2337910/15817280/3c46bd8c-2bcf-11e6-92bb-479148430f9f.png)

My asset manager (photoshopped the thumbnails out for a bit on anonymity, it's not broken):
![image](https://cloud.githubusercontent.com/assets/2337910/15817315/678fdbf4-2bcf-11e6-9ff6-0ae46b9e12b4.png)

**Comment by owldesign** [comment]
Not exactly sure why its broke? It seems to work for me, I'm getting all the assets to show up. Can you remind me of your craft and php versions again?

are you getting any js errors in the console?

**Comment by lexbi** [comment]
No JS errors, nothing in the craft.log, it does let me upload new assets to that asset source in this window, but, it just doesn't list them:
![image](https://cloud.githubusercontent.com/assets/2337910/15852756/53a442bc-2c9a-11e6-84d5-216a8fb0baca.png)

Craft version:
 2.6.2789

Php:
5.6.21 (on my server)
5.6.10 (locally on MAMP)

issue occurs on both environments with local or remote assets.

**Comment by lexbi** [comment]
Is it possible that the field is setup not to allow certain file types? I'm just trying this with jpgs/pngs at the moment

**Comment by owldesign** [comment]
Hmm not sure, I see if I can troubshoot this but so far it was working for me. There isn't any file type validation set up so it should ideally show you everything. Its pretty strange that it still will ask you to overwrite a file that is there. Have you tried other browsers?

**Comment by lexbi** [comment]
Sorry forgot to get back to you about this, just tried in firefox, same as chrome

**Comment by owldesign** [comment]
@lexbi so I updated the way you add notification templates now, you should try it and see if you can add custom logo.

[templates](https://github.com/roundhouse/FormBuilder-2-Craft-CMS#email-notifications)

**Comment by lexbi** [comment]
Great I'll give it a go when I'm back at work thanks so much!

**Comment by lexbi** [comment]
Just tried this, unfortunately it still doesn't work :( I've made a video so you can witness this in action:
https://www.youtube.com/watch?v=bGkmdTFbgfE&feature=youtu.be

Don't know if this will help, but, each time I click a link to a new asset source it fires this action as a POST in the network tab:
`/index.php/admin145/actions/elementIndex/getElements`
Form data includes:

```
context:modal
elementType:Asset
source:folder:1
criteria[status]:
criteria[locale]:en_us
criteria[search]:
criteria[limit]:50
criteria[localeEnabled]:
viewState[mode]:table
viewState[order]:title
viewState[sort]:asc
```

**Comment by owldesign** [comment]
@lexbi ah I have literally no idea what is happening here, I wonder if this is happening for anyone else or just isolated issue?

Couple of other troubleshooting options would be to turn off all other plugins but formbuilder and try again or, do you have another installation of craft you can test on?

**Comment by lexbi** [comment]
This does actually happen on projects and environments for me :(

**Comment by apadeloup** [comment]
Hi, I have exactly the same issue, with the latest Craft version.

**Comment by lexbi** [comment]
Just tried disabling all my plugins apart from formbuilder2, the problem still occurred.

**Comment by lexbi** [comment]
@owldesign maybe you should send this to craft support see if they can suggest anything? Maybe they have experienced this before?

**Comment by mvdt** [comment]
Same issue here, with the latest Craft version.

**Comment by ajcdev** [comment]
Same issue here too

**Comment by benjo696** [comment]
All Element select fields in the plugin have been setup with criteria that only matches locale: **en_us**

Please replace all instances of this with something like **craft.i18n.getCurrentLocale().id**

**Comment by owldesign** [comment]
@benjo696 lates push has this update, not sure if this is relevant to this specific issue? Can someone pull latest and test?

**Comment by owldesign** [comment]
I'm closing this one as the plugins had many updates since this issue was opened.
