### ISSUE TITLE
redirect to same page as form but with query string

### ISSUE THREAD

**Issue by lexbi** [roundhouse/FormBuilder-2-Craft-CMS#55]
I would like to be able to redirect after a form submission to: `{{ craft.request.url }}?message=thankyou` which despite being hardcoded in the form like this: 

    <input type="hidden" name="formRedirect" data-custom-redirect="{{ formSettings.formRedirect.customRedirect }}" value="{{ craft.request.url }}?message=thankyou"> 

It still redirects to `/?message=thankyou` even if you are on an alternative page such as `/about`.
I have tried setting `?message=thankyou` in the backend too, and, using the original code, though the behaviour is the same as hardcoding it.

**Comment by owldesign** [comment]
@lexbi add this field to your form `<input type="hidden" name="redirect" value="{{ craft.request.url }}?message=thankyou">`

Make sure your form settings don't have a custom redirect enabled and it will work. I will need to refactor this later also.

**Comment by lexbi** [comment]
This works great, thank you!
