### ISSUE TITLE
HTML template for "notify submitter" notification email

### ISSUE THREAD

**Issue by joepagan** [roundhouse/FormBuilder-2-Craft-CMS#56]
As a feature request (if you are not already planning to do this) I would love to have the same template options to make it look better for submitter notifications just like you have setup for the admin notifications.

The notification emails are a bit underwhelming at the current time:
![image](https://cloud.githubusercontent.com/assets/2337910/16296845/fb8ad6d4-3925-11e6-8b95-419f546d10fe.png)

**Comment by owldesign** [comment]
You can create templates for both admin and submitters now.
