### ISSUE TITLE
Error on file upload "Craft\AssetFileModel.originalName" is not defined"

### ISSUE THREAD

**Issue by quadri-bvba** [roundhouse/FormBuilder-2-Craft-CMS#57]
I've got a form working, but as soon as I add and enable a file-upload field, i'm getting this error: The attribute "Craft\AssetFileModel.originalName" is not defined. Any ideas on what's causing this?
Craft CMS 2.6.2791 / Formbuilder 2 v0.1.1

**Comment by owlaza** [comment]
I am having the same issue.

**Comment by owldesign** [comment]
File uploads are now fixed, let me know if anything changes.
