### ISSUE TITLE
Delete submissions

### ISSUE THREAD

**Issue by Muffassa** [roundhouse/FormBuilder-2-Craft-CMS#58]
Hi, may i delete form`s submissions without deleting form?

**Comment by owldesign** [comment]
Yes you can, under FormBuilder2 sidebar menu go to `Entries`, click on the id of the entry you want to remove. In the entry detail page there is a button to remove that entry.

**Comment by jeremysanchez** [comment]
Unless I am completely overlooking it, this seems to be missing in the current version.

**Comment by lexbi** [comment]
It would be great if you could select multiple entries and delete them in bulk (I want to delete 50 test emails now a website is live for example).

**Comment by lexbi** [comment]
Any thoughts on this @owldesign ? Can I just delete the table rows, or, would that miss something?

**Comment by owldesign** [comment]
You can delete them from db, I'll see about adding the option to delete multiple
