### ISSUE TITLE
Custom Field Markup in Database

### ISSUE THREAD

**Issue by noahread** [roundhouse/FormBuilder-2-Craft-CMS#61]
It would be great to be able to store custom field data in a field in the CMS rather than in template/custom/inputs. This would allow updating the plugin without fear of overwriting custom markup (I set up custom markup to add the email field type to text inputs). I imagine something like [seomatic](https://github.com/nystudio107/seomatic)’s robots.txt field.

**Comment by owldesign** [comment]
I have pushed update for adding custom field templates please refer to #9 for reference. That should give you ability to make your own input markup without the fear of them getting overwritten.

**Comment by noahread** [comment]
Awesome! Thanks.
