### ISSUE TITLE
FormBuilder 1.4.3 to FormBuilder 2 

### ISSUE THREAD

**Issue by webphpdeveloper** [roundhouse/FormBuilder-2-Craft-CMS#62]
Hello! We are using FormBuilder 1.4.3 and need to upgrade the plugin to use it on craft 2.5 and 2.6 (now we are stuck at 2.4) 
I can not find any information how to migrate from v1 to v2.  Do I simply delete the old plugin and upload this one and all the templates with the forms made in FormBuilder 1.4.3 will work with FormBuilder 2 ? Or its completly something apart and we have to change templates and have new tables in the DB ?

Thank you
Peter

**Comment by owldesign** [comment]
@webphpdeveloper v2 is a major version release and unfortunately it'll be like a new install with new templates.
