### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by migswd** [roundhouse/FormBuilder-2-Craft-CMS#63]
Is there an easy way to translate the error messages and submit button label ?

**Comment by owldesign** [comment]
@migswd  you can find all the available translation strings for front-end here https://github.com/roundhouse/FormBuilder-2-Craft-CMS/blob/master/templates/translation-strings.php

But you'd need to set up your translation files by following this (I'm assuming you already knew that) https://craftcms.com/support/static-translations

Technically you can just change submit button label yourself in the template, but I have added this ability to the form settings anyways. You will need to replace your submit button with this..
`<button type="submit">{% if formSettings.submitButtonText %}{{ formSettings.submitButtonText }}{% else %}Submit Message{% endif %}</button>`

<img width="589" alt="submitbuttontext" src="https://cloud.githubusercontent.com/assets/438764/17453485/485ecef2-5b31-11e6-9f27-d1753b9a46ed.png">
