### ISSUE TITLE
Not all entries visible in entries listing page after database push

### ISSUE THREAD

**Issue by fractorr** [roundhouse/FormBuilder-2-Craft-CMS#64]
I have a site that was up and running for a few days and I made some modifications on our development server and push the entire dev database to the live server except for the form builder tables (craft_formbuilder2_entries and  craft_formbuilder2_forms).  On the dash board it shows there are 4 entries, when I go to the entries listing page it only shows 1 entry.  When I look at the table in the database it shows the 4 records in the craft_formbuilder2_entries table.  

If I view the one entry it is showing and just change the ID on the url to the entries that are not showing I can view the missing entries with now problem.

Any idea why this is happening and how I might fix this?  I have look at all the data and can not find any problems.  Any suggestions of where to look?

**Comment by owldesign** [comment]
Do you have any forms created? How many?
On the entries page is the `All Submissions` tab selected?
I know silly questions, but just making sure?

**Comment by fractorr** [comment]
Yes I have just one form created, and yes All Submissions tab is selected.

In the databse the form has an ID of 1 and all entries have a formId of 1 and the entries title matches the name of the form.

**Comment by owldesign** [comment]
I'm not exactly sure what would cause this, can you think of the significance of the one entry that does show up? Was that entry submitted after you updated the db?

**Comment by fractorr** [comment]
No all 4 entries were in the db before I updated the db.  I can not see any significant difference between the 1 visible entry and the 3 that are not visible.  I have not tried to submit any entries after updating the database as I wanted to get this fixed first.  Here are the basic fields of the 2 tables, the entry with id 225 shows, the others don't.  

**Forms**

id | name | handle | fieldLayoutId
------------ | ------------ | ------------ | ------------
1 | contact form | contactForm | 117


**Entries**

id | formId | title
------------ | ------------ | ------------
224 | 1 | contact form
225 | 1 | contact form
226 | 1 | contact form
227 | 1 | contact form

**Comment by fractorr** [comment]
I tested the form and was able to submit an entry and it shows up in the entries list in the control panel.

**Comment by owldesign** [comment]
So for the dashboard entries count I hit `craft_formbuilder2_entries` directly and get the count of entries.

The entries listing is built using a custom `FormBuilder2` EntryType. I have a feeling that there was a chain broken somewhere in the table relationships. I don't have a lot of db experience to understand exactly how craft connects form submissions to the entrytype and craft elements though. 

`craft_entrytypes`  and `craft_elements` is good tables to look at. 

In `craft_elements` table filter the `FormBuilder2` type and make sure there are at least `4` entries there. If there are not, they most likely lost the relationship somewhere during db merge. 

If you are able to submit and all good, its most likely the db relationship for the EntryType:FormBuilder2

**Comment by fractorr** [comment]
Great, that is problem.  The relationship between craft_elements and craft_formbuilder2_entries.  When I pushed the db from dev to live it screwed up that relationship, it just happened that there was a form entry with an id of 225 on the dev db.  I know what I need to do to fix, it now just a matter of figuring out how to fix it.  So this was my bad not fully understand just how form builder worked with Craft.

Thanks for the help.

**Comment by owldesign** [comment]
OK good luck, let me know if anything else.

**Comment by fractorr** [comment]
After some manually tweaking of data directly in the database I was able to get this fixed.

Thanks for the help.
