### ISSUE TITLE
PHP notice Trying to get property of non-object

### ISSUE THREAD

**Issue by LauraMontgomery** [roundhouse/FormBuilder-2-Craft-CMS#65]
Hi, I've just installed the latest version of FormBuilder2 (a fresh install, not an update) and I'm getting a PHP notice which appears to be complaining about $sproutFieldsPlugin.

I appreciate that there may be something I've done in my set up but as far as I can tell, everything is pretty standard in terms of Craft and my usage of FormBuilder2.

I've attached the screenshots of my error message - helpfully they mean something to you.

I'm also using the latest version of Craft - 2.6.2903

![01](https://cloud.githubusercontent.com/assets/3043327/17396349/ee679ffc-5a2a-11e6-9af9-a91a74e0b638.png)
![02](https://cloud.githubusercontent.com/assets/3043327/17396350/f091dfea-5a2a-11e6-838e-950205706655.png)
![03](https://cloud.githubusercontent.com/assets/3043327/17396352/f31ac0e2-5a2a-11e6-9dd8-545dcae63752.png)

**Comment by owldesign** [comment]
Hey @LauraMontgomery sorry about that, introduced this bug couple of days ago. Latest push should fix this, thanks.

**Comment by LauraMontgomery** [comment]
Great. I've just implemented this and all is sorted now for me. Thanks.
