### ISSUE TITLE
HTML5 required attribute makes Chrome display a tooltip that collide with our validators

### ISSUE THREAD

**Issue by migswd** [roundhouse/FormBuilder-2-Craft-CMS#66]
Big problem here with Chrome and Required HTML5 attribute.
Formerly add the HTML5 required attribute on mandatory fields which makes Chrome display a tooltip with a message "Please Fill out This Field".
So first it is not translatable and is confusing with our own validators.
See here
http://stackoverflow.com/questions/5392882/chrome-popup-please-fill-out-this-field/5393041#5393041

This attribute should not be added. Or have an option to disable it.

**Comment by owldesign** [comment]
If you want to use your own validators just set your fields to not required in your field layout designer. This is not a bug but a valid html5 attribute.

<img width="553" alt="not required" src="https://cloud.githubusercontent.com/assets/438764/17443069/7f44e094-5aed-11e6-97dc-483f5aaa380d.png">
