### ISSUE TITLE
The twig inspect filter does not exist

### ISSUE THREAD

**Issue by mtnorthrop** [roundhouse/FormBuilder-2-Craft-CMS#67]
In the latest version of this plugin, I'm no longer able to view entries because the admin view page throws an Internal Server Error that reports 'Unknown "inspect" filter.'

This seems to be caused by line 77 of `formbuilder2/templates/entries/_view.twig`: `{ file |inspect }}`

The problem is that the "inspect" filter doesn't exist. I've checked the custom Twig filters that are included in the plugin and this one has never been defined.

**Comment by owldesign** [comment]
You are correct it's a craft plugin I use for debugging. I have left that in there by mistake, it's out now, pull latest. Thanks
