### ISSUE TITLE
Output dropdown label in notification

### ISSUE THREAD

**Issue by dguillory** [roundhouse/FormBuilder-2-Craft-CMS#69]
Thanks much for the plugin and all of the recent updates – it's fantastic.

I'm wondering if there's an easy way to output the label of dropdown fields in addition to the value. Being able to use a dropdown to select a recipient for the notification is great, but it would be really helpful to see the selected label (e.g. 'Sales Inquiry') in the notification instead of just the email it was sent to.

**Comment by owldesign** [comment]
Yes, I think so. However, it might need to wait till the next big push. I'm working on email templates editor at the moment and this is something that I can include there. Hopefully it will be worth the wait...

**Comment by dguillory** [comment]
Sounds awesome, thanks. Looking forward to it.

**Comment by owldesign** [comment]
@dguillory so... I "sort of" made a fix for this, I think this is the best option for now.

First of I added [templates](https://github.com/roundhouse/FormBuilder-2-Craft-CMS#email-notifications) check that out. 

For your specific issue this is what you will need to do to achieve it (I have the code in place so going forward I will be putting this into documentation).

Basically when you making that drop down field add `|Your Label Name` to your values. I'm using the `|` to split those up so make sure the pipe is in there!

Let me know if that works?

<img width="516" alt="screen shot 2016-08-16 at 11 41 34 pm" src="https://cloud.githubusercontent.com/assets/438764/17726991/fee72f48-640a-11e6-91b3-880f81c3915b.png">

**Comment by dguillory** [comment]
This works perfectly, thanks!
