### ISSUE TITLE
update to craft 2.5 will be error

### ISSUE THREAD

**Issue by jimmy0816** [roundhouse/FormBuilder-2-Craft-CMS#7]
back-end view was broken. and click entry not showing

**Comment by owldesign** [comment]
I had a branch for craft25 updates. Now that its officially out I updated master branch to the new stuff. Try to pull and check if it fixed for you.

**Comment by jimmy0816** [comment]
appreciate, it was fixed for me. just plugins index look like a little weird.maybe can change it.
i have another issue. have way can edit entry in back-end ?because it's only showing now.

**Comment by terrysmyth** [comment]
Is this the Error you are referring too?

Parse error: syntax error, unexpected '[' in /home/dmrhk2015/public_html/craft/plugins/formbuilder2/controllers/FormBuilder2Controller.php on line 54

I dont know how to fix it. I simply installed the plugin and the first time i click on formbuilder2 i got the above error.

**Comment by owldesign** [comment]
Are you guys still having issues?

@terrysmyth can you pull latest and let me know if you still have issues, you need php 5.4 as well for this to work, closing ticket for now.

**Comment by terrysmyth** [comment]
Hey Vadim,

Thanks for your help and updates. Everything is fine now. I've moved to
digital ocean as my servers. It was only the php version that was causing
the problems.

Regards,

Terry
