### ISSUE TITLE
Delete option missing

### ISSUE THREAD

**Issue by jeremysanchez** [roundhouse/FormBuilder-2-Craft-CMS#70]
This was closed as issue #58,  but unless I am completely overlooking it, the delete options seems to be missing from the submission entries detail page in the current version.

**Comment by jeremysanchez** [comment]
Looks like the problem is in line 107 of entries/_view.twig. 

`{% if currentUser == 'admin' or settings.canDoActions %}`

Seems like it is looking for a *specific* user named 'admin'. When I plug my own username in there, the delete button shows up.

**Comment by jeremysanchez** [comment]
Also, the delete button shows up properly if "Allow non-admins" is toggled ON.

**Comment by owldesign** [comment]
Yeah that's my bad it should have been `currentUser.admin`. Pushed up a fix, thanks!
