### ISSUE TITLE
tab name creates class on Fieldset element with question mark character

### ISSUE THREAD

**Issue by lexbi** [roundhouse/FormBuilder-2-Craft-CMS#72]
Would be better if it used the tab handle, rather than created a slug out of it imo.

![image](https://cloud.githubusercontent.com/assets/2337910/17925900/b8a4eeb2-69e6-11e6-9d2d-69f4ff9d9da1.png)

**Comment by owldesign** [comment]
@lexbi depending how you're using the plugin. If you use the 'Forms' custom field I can put whatever we want for the tab classes, but if you're manually adding the form mark up to your front-end template, you can put whatever you want for the class.

See line `22`, I'm just getting tab name and cleaning it up with twig filters.  I don't think tabs have handle names? So filtering the name was best approach. Anyways, I think its up to the developer to decided what class they want to put there.

![tabs](https://cloud.githubusercontent.com/assets/438764/17940276/3715efb6-69e3-11e6-943e-7ea9a1a2443a.png)

**Comment by lexbi** [comment]
Sorry, I know this is definitely my responsibility! I was just pointing this out as a problem that I encountered when using the sampleForm, I didn't know tabs did not have handles!
Maybe this could be solved with a [a-zA-Z0-9] replace filter.

**Comment by owldesign** [comment]
OK I updated `templates/forms/frontend.twig` with new twig filter.

You can use this in your form `<fieldset class="{{ tab.name | camelCase(tab.name) }}">` this filter provides handle name like class.
