### ISSUE TITLE
It appears that the datefield requires user to be logged in, utilises "currentUser"

### ISSUE THREAD

**Issue by lexbi** [roundhouse/FormBuilder-2-Craft-CMS#73]
![image](https://cloud.githubusercontent.com/assets/2337910/17934278/329e7300-6a0f-11e6-8d7b-f9273db5fe86.png)

**Comment by owldesign** [comment]
Fixed, thanks for point it out!

**Comment by lexbi** [comment]
No probs &  thanks!
