### ISSUE TITLE
Plugin breaks Control Panel after updating to Craft 2.6.2922

### ISSUE THREAD

**Issue by danielparas** [roundhouse/FormBuilder-2-Craft-CMS#74]
Hi, first of all thanks for this great plugin! 

Just want to report a major issue. After updating to the latest version of Craft (Craft CMS 2.6.2922 released today) my control panel broke: dashboard fails to load, entires section does not load, login does not work etc..

Browser console logs:

```
GET http://craft.dev/admin/resources/lib/garnish-0.1.1.min.js?x=XkdcXn8LE 404 (Not Found)
craft.js:1483Uncaught ReferenceError: Garnish is not defined
```

After removing the FormBuilder plugin from the plugins folder the admin control panel functionality is restored to normal. I tried adding the latest release but the DB update does not complete since the same issue crops up, thus breaking the Control Panel.

All worked well with previous releases.

Thanks
Daniel

**Comment by owldesign** [comment]
This seems like the new update breaking it, I'll investigate if formbuilder breaks something.

**Comment by danielparas** [comment]
Thanks @owldesign !

**Comment by owldesign** [comment]
@danielparas it looks like a Craft issue, you need to clear the app cache in the `admin/settings` under Tools.

![screen shot 2016-08-26 at 1 40 19 pm](https://cloud.githubusercontent.com/assets/438764/18019795/adffcb32-6b92-11e6-9830-61891c6e35ff.png)

**Comment by danielparas** [comment]
ah I deleted the cache manually by deleting files under /storage/runtime/cache but I guess that doesn't delete everything.

Thanks - solved it! :)
