### ISSUE TITLE
E-mail input field should be set to type="email". Now it results in a system error.

### ISSUE THREAD

**Issue by noregt** [roundhouse/FormBuilder-2-Craft-CMS#75]
Because it is set as a text field, it will accept random characters.
As a result I get a system error when submitting:

Internal Server error

E-mail error: Invalid address: asddadf

I tried setting my custom html, but that results in new problems, being that the system sends all mails to the admin and none to the submitter.

**Comment by owldesign** [comment]
@noregt do you mind sending me your form's settings? if possible screenshots from each of these tabs. Thanks


![screen shot 2016-08-31 at 9 33 33 am](https://cloud.githubusercontent.com/assets/438764/18137628/0410d72c-6f5e-11e6-8ec0-042629138dc6.png)

**Comment by noregt** [comment]
![schermafbeelding 2016-09-01 om 09 35 59](https://cloud.githubusercontent.com/assets/534396/18159152/b54b5c78-7027-11e6-8a2f-b8a6cc4b71e7.PNG)
![schermafbeelding 2016-09-01 om 09 34 43](https://cloud.githubusercontent.com/assets/534396/18159154/b54d2f80-7027-11e6-8848-9ef3b94dabd9.PNG)
![schermafbeelding 2016-09-01 om 09 34 33](https://cloud.githubusercontent.com/assets/534396/18159153/b54c92aa-7027-11e6-9932-930b02a69a44.PNG)
![schermafbeelding 2016-09-01 om 09 33 56](https://cloud.githubusercontent.com/assets/534396/18159155/b54d6338-7027-11e6-92b1-2cc80d321782.PNG)
![schermafbeelding 2016-09-01 om 09 33 46](https://cloud.githubusercontent.com/assets/534396/18159156/b54dea88-7027-11e6-9523-b1f351cd83c0.PNG)

**Comment by owldesign** [comment]
Hey @noregt see #79 for options. Like I mentioned there you have to make your own field or use a different plugin that provides the html5 input types. FormBuilder2 only uses the field types craft provides out of the box.
