### ISSUE TITLE
Admin notification is sent twice

### ISSUE THREAD

**Issue by noregt** [roundhouse/FormBuilder-2-Craft-CMS#77]
When submitting a form I first get the admin notification, then the submitter notification and then again the admin notification

**Comment by owldesign** [comment]
@noregt not exactly sure why that would happen. Make sure your `Custom Email Field` doesn't have any selection maybe?

If you don't mind sending me screenshot of your `Email Settings` tab I would troubleshoot

**Comment by noregt** [comment]
You're right, with no `Custom Email Field` there are only two mails. But I do need that e-mail field, because the web admin will reply to that mail with the result that it will be send to the admin and not to the submitter.
![schermafbeelding 2016-09-01 om 12 44 26](https://cloud.githubusercontent.com/assets/534396/18164766/ec50a0ec-7041-11e6-9c05-53314f9a1c53.PNG)

**Comment by noregt** [comment]
Sorry for the confusion, but this appears to be very closely related to issue #78. Took me some time to figure that out. The double admin mail has to do with the 'from mail' not working properly I guess

**Comment by owldesign** [comment]
@noregt so you are using the `Custom Email Field` incorrectly for the admin notification. See this ticket for usage of that field #46. You only use that field if your form has a drop down of values that depending on what value you choose will send email to specific email address. Look at that ticket for more clarity. 

I'll try to update that field in the future with more instructions so users don't get confused.

**Comment by owldesign** [comment]
Closing this, `Reply To` settings was added, use that to set to submitters email field.
