### ISSUE TITLE
Notifications for submitter and admin; from address wrong and e-mail submission field empty

### ISSUE THREAD

**Issue by noregt** [roundhouse/FormBuilder-2-Craft-CMS#78]
Based on issue #76 it's still a bit messy.
- First mail is to the submitter and uses the template and subject line for the admin. From address is the admin address
  -Second mail is sent to the admin, From address is again the admin address where it should be the submitter's address
- Third mail (a bit later) to the submitter is correct. (see issue #77),

I suspect that your plugin tries to send the admin mail with the custom email field as the 'from mail' but instead first sends the admin mail with the 'to mail' from the custom field and then again to the admin without that field used.

Also, in these mails the e-mail field in the submission data is left blank (should contain that field)

**Comment by noahread** [comment]
I am having the same issue

**Comment by owldesign** [comment]
Latest push has `Reply To` setting, use that to set reply to email field.
