### ISSUE TITLE
Create a Form button/link?

### ISSUE THREAD

**Issue by kemmerly** [roundhouse/FormBuilder-2-Craft-CMS#8]
After creating one form I can't seem to find a link or button to create another form. Assumed it would be on the Forms tab but I'm not seeing it. Using Craft 2.5 and FB2 0.1.

The screenshot shows a Quick Link for Create New Form but my screen doesn't look like the one in the screenshot.

Thanks.

![formbuilder](https://cloud.githubusercontent.com/assets/1459061/11958257/ccdf0160-a894-11e5-994a-46d5793a25d9.jpg)

**Comment by owldesign** [comment]
Sorry about that @kemmerly, I updated master branch, you should now see buttons next to section titles to the right.

**Comment by kemmerly** [comment]
That works. Thanks for the quick response. I could add new forms by navigating to the URL listed in the controller file but couldn't figure out why I wasn't seeing a link.

Well designed plugin - I appreciate you sharing it.
