### ISSUE TITLE
Template displays html tags

### ISSUE THREAD

**Issue by torbjornlarssen** [roundhouse/FormBuilder-2-Craft-CMS#80]
After I save a template with linebreaks, they show up as visible `<br>` in the email and also in the CP-template-editor if I open it again.

**Comment by owldesign** [comment]
@torbjornlarssen fixed. I had to do a database change for the columns so you'll need to update your templates..basically it was saving as `<br>` tags to db and I want it to just save it as new lines.

So...whenever there is a `<br>` tag in your textarea delete it and replace with space!

Let me know if any questions. Thanks.
