### ISSUE TITLE
How to show hard coded fields in the submission entry and email

### ISSUE THREAD

**Issue by daituzhang** [roundhouse/FormBuilder-2-Craft-CMS#82]
I have a quite complicated form, so I didn't use the fields function and just hard coded them.
But the submission content were shown as empty in the entries and the notification emails.

Is there any way I can show those fields up? Even just in emails?
If I can show them up in email, what will be the variable rule I should follow in email template?

Thank you

**Comment by owldesign** [comment]
Oh yeah its not going to work like that. You have to create those fields in craft for them to show up. I might look at options in the future for hardcoded fields but not priority right now.

To get the fields to show up in email and submission all you have to do is just create those fields with the same handle name as your input `name="someName"`. You don't have to attach the created fields to your forms but it has to be in the system and the custom input name has to match the handle name of created fields. Does that make sense?

**Comment by daituzhang** [comment]
AHA!! Thank you, that makes sense!
And thank you for this awesome plugin again, I've been using it for years.

**Comment by owldesign** [comment]
You're welcome!
