### ISSUE TITLE
When no logo is set in custom submitter notification template, it fails.

### ISSUE THREAD

**Issue by lexbi** [roundhouse/FormBuilder-2-Craft-CMS#83]
![image](https://cloud.githubusercontent.com/assets/2337910/18344164/204c3228-75ae-11e6-988a-2186a3d9a872.png)

**Comment by lexbi** [comment]
Hmm I'm actually getting this now despite removing the template from the form, I have also deleted the template, very strange

**Comment by lexbi** [comment]
Ok so this is actually when no template is selected despite having the "admin notification" area selected.

**Comment by owldesign** [comment]
Latest push should fix this, thanks for tracking it down.
