### ISSUE TITLE
Bad Request when using Ajax

### ISSUE THREAD

**Issue by daituzhang** [roundhouse/FormBuilder-2-Craft-CMS#84]
When I activate AJAX for a form, and submit it in the front end, I get this error message:

Bad Request
The request could not be understood by the server due to malformed syntax.

The form works perfectly without AJAX.

I'm on Craft Craft CMS 2.6.2791 using sendmail on lamp server.

**Comment by carlosperez** [comment]
I'm seeing this as well. Sometimes it works fine, other times it looks I get this.

**Comment by owldesign** [comment]
I updated ajax submission functionality. Closing this for now.
