### ISSUE TITLE
Can the jquery datepicker ui be optional on date fields?

### ISSUE THREAD

**Issue by joepagan** [roundhouse/FormBuilder-2-Craft-CMS#85]
Just found out that formbuilder2 initiates datepicker on my date field!
![image](https://cloud.githubusercontent.com/assets/2337910/18552681/63dcc4a6-7b55-11e6-8666-278d928d10a1.png)

I tend to like leaving these fields for browsers to handle now, here's chrome for example:
![image](https://cloud.githubusercontent.com/assets/2337910/18552731/a073d814-7b55-11e6-9515-7eeb5511a1ad.png)

**Comment by lexbi** [comment]
Just found that this is actually set in the default datefield template, this can of course now be overwritten if you want to remove it for the time being.

**Comment by owldesign** [comment]
@joepagan you can now disable date/time picker from the form settings.

![screen shot 2017-07-20 at 2 49 11 pm](https://user-images.githubusercontent.com/438764/28440326-a17dc27c-6d5a-11e7-9096-e85368f0ab75.png)

**Comment by joepagan** [comment]
Cheers dude!
