### ISSUE TITLE
Customizing Submit Button Text

### ISSUE THREAD

**Issue by kevibethink** [roundhouse/FormBuilder-2-Craft-CMS#87]
Is there any way to customize the text on the submit button? The form I'm using doesn't submit a message, so I just want it to say "Submit", but when I go into the templates/forms/frontend.twig and change it there it stays the same? Where is this value stored for me to edit? I've tried editing the code directly in the plugin and I even did a search replace on the whole plugin directory looking for the "Submit Message" string to replace, and cleared my browser cache and Craft cache, but it still keeps saying Submit message instead of just submit. This is really something that should be a form setting in the admin.

Thanks

**Comment by owldesign** [comment]
@kevibethink it is in the form settings, check screenshot bellow. Make sure you have the latest repo and this line for submit button html 

`<button type="submit">{% if formSettings.submitButtonText %}{{ formSettings.submitButtonText }}{% else %}Submit Message{% endif %}</button>` <- see sampleForm.twig for example.

![Uploading Screen Shot 2016-09-19 at 10.02.45 AM.png…]()
