### ISSUE TITLE
Can you add the ability to create rows and columns in the form builder 

### ISSUE THREAD

**Issue by ischemic** [roundhouse/FormBuilder-2-Craft-CMS#88]
That would be super helpful!

**Comment by owldesign** [comment]
@ischemic can you elaborate more what you mean? Give me an example use case please.

**Comment by Visiluna** [comment]
I'd like to +1 this request.

My use case is for entering a postal address.

Currently, FormBuilder renders my fields as:

```
[ Name ]
[ Email ] 
[ Address ]
[ City ]
[ State ]
[ Zip/Postal Code ]
```

I need some way to arrange the fields as:

```
[ Name ]
[ Email ]
[ Address ]
[ City ] [ State ] [ Zip/Postal Code ]
```

Thanks.

**Comment by owldesign** [comment]
Might be an overkill, since this can just be achived with css. I will make a video tutorial on how to achive that.

**Comment by rizzledizzle** [comment]
If anyone is interested i got the desired effect above with something along these lines:
```
{% for tab in tabs %}
<div class="grid">
	{% set fields = tab.getFields() %}
	{% set numOfFields = fields|length %}
	{% switch numOfFields  %}
	  	{% case 1 %}
	  	{% set class = "whole" %}
	  	{% case 2 %}
	  	{% set class = "half" %}
	  	{% case 3 %}
	  	{% set class = "one-third" %}
	  	{% default %}
	  	{% set class = "half" %}
	{% endswitch %}

	{% for field in fields %}
		<div class="unit {{class}} {{field.getField().type|kebab}}">
		  {% set value = value is defined ? value : [] %}
		  {% set input = craft.formBuilder2.getInputHtml(field,value) %}
		  {{ input |raw }}
	  	</div>
	{% endfor %} 
</div>
{% endfor %} 
```
basically i change the class dependant on the amount of fields in each tab, that affects whether it is full width, two col layout or three col layout. Any higher and it just defaults to two fields per row in this example. markup/class names will change dependant on your framework etc. but the principal would remain the same.

**Comment by owldesign** [comment]
Closing, can be done with css or via above example.
