### ISSUE TITLE
Hidden field value not being displayed.

### ISSUE THREAD

**Issue by farrellScript** [roundhouse/FormBuilder-2-Craft-CMS#89]
I'm trying to use Sprout Fields with FormBuilder2 but when I use a hidden field the value doesn't show in the HTML. So I'm seeing this: 
`<input type="hidden" id="foo" class="foo" name="foo">`
when I think I should be seeing this:
`<input type="hidden" id="foo" class="foo" name="foo" value="bar">`

**Comment by owldesign** [comment]
Latest master should have a fix for this, thanks for catching it.
