### ISSUE TITLE
Form file upload saves to wrong directory

### ISSUE THREAD

**Issue by m-soyka** [roundhouse/FormBuilder-2-Craft-CMS#90]
When I upload a PDF file from the FormBuilder's front-end, the submission is successful, but it places the newly uploaded asset into an unspecified directory. Any ideas why this may be occurring?

Appreciate your help.

![applying-field-to-form](https://cloud.githubusercontent.com/assets/16545161/19285153/03845a84-8fc7-11e6-9821-93d93b107427.jpg)
(Applying the created asset field to the form)

![formediting](https://cloud.githubusercontent.com/assets/16545161/19285151/037ff98a-8fc7-11e6-8497-07b6975039e5.jpg)
(editing the Formbuilder Form to accept file uploads)

![assetsourcefor-upload](https://cloud.githubusercontent.com/assets/16545161/19285154/0388b804-8fc7-11e6-85a2-d50ab5b2d87b.jpg)
(Creating the asset source directory in uploads)

![fileassetfieldedit](https://cloud.githubusercontent.com/assets/16545161/19285152/03835c06-8fc7-11e6-9ed0-b01e683b35e5.jpg)
(Asset field editing)

**Comment by hungle88** [comment]
In Step "Creating the asset source directory in uploads"
I think the URL Input should be an URL, not a path. 
Haven't tried it, though.
