### ISSUE TITLE
AJAX forms not reset correctly when using 2 or more forms on a page

### ISSUE THREAD

**Issue by monkeyArms** [roundhouse/FormBuilder-2-Craft-CMS#92]
When a page has multiple AJAX-enabled forms, only the first form on the page is reset after successful submission.
This is due to /resources/js/ajaxsubmit.js (line 4):
`theForm = $('form.formbuilder2');`
and line 21:
`return theForm[0].reset();`

**Comment by Visiluna** [comment]
I am also experiencing this issue alongside my [other multiple form issue](https://github.com/roundhouse/FormBuilder-2-Craft-CMS/issues/100).

**Comment by owldesign** [comment]
Fixed.
