### ISSUE TITLE
Adding Column to the form

### ISSUE THREAD

**Issue by waswebb** [roundhouse/FormBuilder-2-Craft-CMS#93]
Hi,

I think you have build a very cool Plugin! I link it very.

But it would be nice to have the option to wrap Fields in Column.

Like this:
![bildschirmfoto 2016-10-25 um 17 21 33](https://cloud.githubusercontent.com/assets/21307389/19692436/3936800a-9ad8-11e6-9ced-80555ee08c70.png)

**Comment by owldesign** [comment]
No real plan to add specific customization to the columns but you can currently achieve it by using fieldsets. Here are some example screenshots.. The `Add Fieldset Tab` acts like a column by adding a fieldset tag around whatever fields you include under it. 

<img width="493" alt="final" src="https://cloud.githubusercontent.com/assets/438764/21837612/1ed9f732-d782-11e6-9b42-bd73e5ac2c9d.png">
<img width="525" alt="setup" src="https://cloud.githubusercontent.com/assets/438764/21837611/1ed9da54-d782-11e6-8733-e6d00fffef2b.png">

Then you can just css it however you want to. Let me know if you have more questions.
