### ISSUE TITLE
Show input field after clicking radio button.

### ISSUE THREAD

**Issue by SeeklesBodil** [roundhouse/FormBuilder-2-Craft-CMS#94]
Hi guys,

Is is possible to only show a input field after clicking on a radio button?

Thank you in advance!

**Comment by owldesign** [comment]
Not out of the box. But you can always add your own js to do that after field were rendered in?

**Comment by SeeklesBodil** [comment]
Do you maybe have an example?

Verstuurd vanaf mijn iPhone
