### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by LauraMontgomery** [roundhouse/FormBuilder-2-Craft-CMS#97]
Hi, I had a bit of an issue outputting a form by the ID and after 40 minutes, I stumbled upon the solution. It looks like the readme file needs a small update of `getFormEntryById` to `getFormById` as shown in the [Custom Redirects](https://github.com/roundhouse/FormBuilder-2-Craft-CMS#custom-redirects) section.

**Comment by owldesign** [comment]
Updated, thanks!
